apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications-helm-apps-set
  namespace: argocd
spec:
  generators:
  - git:
      revision: master
      repoURL: https://github.com/MatiWall/application-values.git
      directories:
        - path: pejzen
      values:
        namespace: pejzen
  - git:
      revision: master
      repoURL: git@github.com:MatiWall/application-values.git
      directories:
        - path: mwstack/authenticator
        - path: mwstack/webhook-forwarder
      values:
        namespace: mwstack
  - git:
      revision: master
      repoURL: https://github.com/MatiWall/application-values.git
      directories:
        - path: fittracker/fittracker-backend
      values:
        namespace: fittracker
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/MatiWall/application-values.git
        helm:
          valueFiles:
            - values.yaml
        path: '{{ path }}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
