apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications-manifest-apps-set
  namespace: argocd
spec:
  generators:
    - git:
        revision: main
        repoURL: https://github.com/MatiWall/HomeLab.ClusterApplications.Manifests.git
        directories:
          - path: mwstack/webhook-forwarder
        values:
          namespace: mwstack
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: https://github.com/MatiWall/homelab.cluster-tools.application-values.git
        path: '{{ path }}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

